### ISSUE TITLE
0.6.1 npm package is broken

### ISSUE THREAD

**Issue by sh-dave** [lix-pm/haxeshim#5]
this is the beginning of the ```haxeshim/bin/haxeshim.js```

```
#!/usr/bin/env node

#!/usr/bin/env node

// Generated by Haxe 3.4.0 
```

this is the error:
```
d:\......\haxe-node-boilerplate\node_modules\haxeshim\bin\haxeshim.js:3
#!/usr/bin/env node
^
SyntaxError: Invalid or unexpected token
    at Object.exports.runInThisContext (vm.js:78:16)
    at Module._compile (module.js:543:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:420:7)
    at startup (bootstrap_node.js:139:9)
    at bootstrap_node.js:535:3
```

Removing the 2nd ```#!/usr/bin/env node``` fixes the problem.

**Comment by back2dos** [comment]
Yeah, sorry about that. I put in a guard that should prevent double prefixing and published a fix on npm ;)
