### ISSUE TITLE
Broken pipe when compiling to C++

### ISSUE THREAD

**Issue by Gama11** [lix-pm/haxeshim#56]
Sort of a followup for #51:

I've just published vshaxe 2.18.0 which modifies the PATH correctly so haxeshim has the right Haxelib. This seems to work perfectly fine for Java and C#, but there's still something wrong with C++.

This is what I get when running the default build task of https://github.com/Gama11/HaxeRepro/tree/lix-hxcpp-broken-pipe with `enableCompilationServer: false` (but it also reproduces on the command line if you call `haxe.cmd` directly and modify the `PATH` as before):

```
> Executing task: c:/Users/Jens/GitHub/HaxeProjects/HaxeRepro/node_modules/.bin/haxe.cmd build.hxml -cpp export/cpp -cmd cmd /C export\cpp\Main-debug.exe <

events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: EPIPE: broken pipe, write
    at Socket._write (internal/net.js:58:25)
    at doWrite (_stream_writable.js:410:12)
    at writeOrBuffer (_stream_writable.js:394:5)
    at Socket.Writable.write (_stream_writable.js:294:11)
    at Y.path (c:\Users\Jens\GitHub\HaxeProjects\HaxeRepro\node_modules\lix\bin\haxelibshim.js:2:90346)
    at Y.dispatch (c:\Users\Jens\GitHub\HaxeProjects\HaxeRepro\node_modules\lix\bin\haxelibshim.js:2:91517)
    at Y.main (c:\Users\Jens\GitHub\HaxeProjects\HaxeRepro\node_modules\lix\bin\haxelibshim.js:2:89749)
    at Object.Ce.invoke (c:\Users\Jens\GitHub\HaxeProjects\HaxeRepro\node_modules\lix\bin\haxelibshim.js:2:124916)
    at Ze.handle (c:\Users\Jens\GitHub\HaxeProjects\HaxeRepro\node_modules\lix\bin\haxelibshim.js:2:128918)
    at Be.f (c:\Users\Jens\GitHub\HaxeProjects\HaxeRepro\node_modules\lix\bin\haxelibshim.js:2:128832)
Emitted 'error' event at:
    at onwriteError (_stream_writable.js:425:12)
    at onwrite (_stream_writable.js:456:5)
    at Socket._write (internal/net.js:62:14)
    at doWrite (_stream_writable.js:410:12)
    [... lines matching original stack trace ...]
    at Object.Ce.invoke (c:\Users\Jens\GitHub\HaxeProjects\HaxeRepro\node_modules\lix\bin\haxelibshim.js:2:124916)
haxelib run hxcpp Build.xml haxe -Ddebug -Ddump="pretty" -Dhaxe="4.0.5" -Dhaxe3="1" -Dhaxe4="1" -Dhaxe_ver="4.005" -Dhxcpp_api_level="400" -Dhxcpp_smart_strings="1" -Dsource-header="Generated by Haxe 4.0.5" -Dstatic="1" -Dtarget.name="cpp" -Dtarget.static="true" -Dtarget.sys="true" -Dtarget.threaded="true" -Dtarget.unicode="true" -Dtarget.utf16="true" -Dutf16="1" -I"source/" -I"" -I"C:\\Users\\Jens\\AppData\\Roaming/haxe/versions/4.0.5/std/cpp/_std/" -I"C:\\Users\\Jens\\AppData\\Roaming/haxe/versions/4.0.5/std/"
source/Main.hx:3: Test
```

Somehow it still compiles and runs despite the broken pipe, but something is clearly wrong. With `"haxe.enableCompilationServer": true`, the task just hangs without any output, I'm assuming that's related to this EPIPE error.

**Comment by Gama11** [comment]
\o/ That was quick.

Looks like it fixed both cases too (with and without compilation server)
