### ISSUE TITLE
withNeko is undefined

### ISSUE THREAD

**Issue by kevinresol** [lix-pm/haxeshim#7]
With haxeshim 0.8.1+, I got the following:
(0.8.0 and below is fine though)

```
npm run haxe server_tests.hxml
> haxe "server_tests.hxml"

/Users/kevin/Codes/wkphc-hierarchy/node_modules/haxeshim/bin/haxeshim.js:1081
                        if(withNeko.indexOf(_gthis.nekoPath) != -1) {
                                   ^

TypeError: Cannot read property 'indexOf' of undefined
    at addNeko (/Users/kevin/Codes/wkphc-hierarchy/node_modules/haxeshim/bin/haxeshim.js:1081:15)
    at haxeshim_HaxeInstallation.env (/Users/kevin/Codes/wkphc-hierarchy/node_modules/haxeshim/bin/haxeshim.js:1092:4)
    at haxeshim_HaxeCli [as __class__] (/Users/kevin/Codes/wkphc-hierarchy/node_modules/haxeshim/bin/haxeshim.js:815:35)
    at Function.haxeshim_HaxeCli.main (/Users/kevin/Codes/wkphc-hierarchy/node_modules/haxeshim/bin/haxeshim.js:841:2)
    at /Users/kevin/Codes/wkphc-hierarchy/node_modules/haxeshim/bin/haxeshim.js:2147:18
    at Object.<anonymous> (/Users/kevin/Codes/wkphc-hierarchy/node_modules/haxeshim/bin/haxeshim.js:2148:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
```

**Comment by kevinresol** [comment]
Inspecting the generated js, the null case is actually omited:

```js
var _g = process.env[varName];
var withNeko = _g;
if(withNeko.indexOf(_gthis.nekoPath) != -1) {
	value = withNeko;
} else {
	var v = _g;
	value = "" + v + sep + _gthis.nekoPath;
}
ret[varName] = value;
```

**Comment by back2dos** [comment]
I think this is because I didn't publish the fix with the null case yet. Can you try v0.8.2?

**Comment by kevinresol** [comment]
yeah it works now
